### User registration end point
POST http://localhost:5001/api/user/register
Content-Type: application/json

{
  "name":"Siva Ganesh",
  "email":"testregister@mail.com",
  "password":"sivaganeshrk"
}

###User login end point
POST http://localhost:5001/api/user/auth
Content-Type: application/json

{
  "email":"sivaganesh@mail.com",
  "password":"sivaganeshrk"
}

### Get the logged in user data end point
GET http://localhost:5001/api/user/auth
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY5YmM1ZmE0YjQ5NmI0YmU4YzdkZGJjIn0sImlhdCI6MTYwNDA2OTE0NywiZXhwIjoxNjA2MTg5MTQ3fQ._-u6IC0aJsu6U4MReIe6vxSAiHqIAJ0nlAdLjfDNam8

### Verifing referral code end point
GET http://localhost:5001/api/user/referral/1b697eac4337

#### User register using referal code end point
POST http://localhost:5001/api/user/referral/b78294ee65d0
Content-Type: application/json


{
  "name":"Siva Ganesh",
  "email":"test1234@mail.com",
  "password":"sivaganeshrk"
}

#### Admin register end point
POST http://localhost:5001/api/admin/register
Content-Type: application/json

{
  "name":"Siva Ganesh",
  "email":"sivadoog0808@gmail.com",
  "password":"sivaganeshrk"
}

#### Admin login end point
POST http://localhost:5001/api/admin/auth
Content-Type: application/json

{
  "email":"sivadoog0808@gmail.com",
  "password":"sivaganeshrk"
}

### Get logged in admin details
GET http://localhost:5001/api/admin/auth
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY5YzIyNzU5N2RlYzAwNTFjMWVkMjg5In0sImlhdCI6MTYwNDA2OTM3MCwiZXhwIjoxNjA2MTg5MzcwfQ.nk-tJFxtuqA-g1HpjHlOzV5j79hzZ9GuuERrvRLaV5Y